{
    "links": [
        [
            1,
            3
        ],
        [
            4,
            7
        ],
        [
            5,
            9
        ],
        [
            10,
            8
        ],
        [
            11,
            6
        ]
    ],
    "node_positions": [
        {
            "x": 46.0,
            "y": 267.0
        },
        {
            "x": 328.0,
            "y": 292.0
        },
        {
            "x": 621.0,
            "y": 207.0
        },
        {
            "x": 619.0,
            "y": 363.0
        },
        {
            "x": 328.0,
            "y": 414.0
        },
        {
            "x": 330.0,
            "y": 177.0
        }
    ],
    "nodes": [
        {
            "key": 87,
            "string_id": "KeyboardNode"
        },
        {
            "string_id": "BranchNode"
        },
        {
            "animationName": "Armature|running",
            "string_id": "AnimationChangerNode"
        },
        {
            "animationName": "Armature|idle",
            "string_id": "AnimationChangerNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        }
    ]
}