{
    "links": [
        [
            1,
            6
        ],
        [
            7,
            10
        ],
        [
            13,
            17
        ],
        [
            16,
            18
        ],
        [
            19,
            3
        ],
        [
            5,
            9
        ],
        [
            23,
            20
        ],
        [
            24,
            12
        ],
        [
            25,
            21
        ],
        [
            11,
            22
        ],
        [
            29,
            26
        ],
        [
            30,
            27
        ],
        [
            35,
            31
        ],
        [
            32,
            37
        ],
        [
            36,
            38
        ],
        [
            39,
            40
        ],
        [
            34,
            44
        ],
        [
            41,
            43
        ],
        [
            45,
            28
        ],
        [
            49,
            46
        ],
        [
            50,
            47
        ],
        [
            53,
            48
        ],
        [
            42,
            51
        ],
        [
            8,
            52
        ],
        [
            60,
            57
        ],
        [
            61,
            58
        ],
        [
            55,
            62
        ],
        [
            69,
            65
        ],
        [
            66,
            71
        ],
        [
            70,
            72
        ],
        [
            73,
            74
        ],
        [
            76,
            63
        ],
        [
            64,
            59
        ],
        [
            81,
            77
        ],
        [
            78,
            83
        ],
        [
            82,
            84
        ],
        [
            104,
            86
        ],
        [
            105,
            95
        ],
        [
            101,
            106
        ],
        [
            108,
            111
        ],
        [
            113,
            115
        ],
        [
            118,
            88
        ],
        [
            119,
            112
        ],
        [
            85,
            90
        ],
        [
            136,
            120
        ],
        [
            123,
            133
        ],
        [
            128,
            124
        ],
        [
            125,
            130
        ],
        [
            129,
            131
        ],
        [
            132,
            137
        ],
        [
            138,
            135
        ],
        [
            139,
            122
        ],
        [
            140,
            121
        ],
        [
            141,
            134
        ]
    ],
    "node_positions": [
        {
            "x": 4.0,
            "y": 241.0
        },
        {
            "x": 225.0,
            "y": 78.0
        },
        {
            "x": 223.0,
            "y": 281.0
        },
        {
            "x": 467.0,
            "y": 214.0
        },
        {
            "x": -219.0,
            "y": -16.0
        },
        {
            "x": -224.0,
            "y": 109.0
        },
        {
            "x": 2.0,
            "y": 19.0
        },
        {
            "x": 703.0,
            "y": 109.0
        },
        {
            "x": 463.0,
            "y": 27.0
        },
        {
            "x": -444.0,
            "y": -37.0
        },
        {
            "x": 472.0,
            "y": 126.0
        },
        {
            "x": 692.0,
            "y": 441.0
        },
        {
            "x": 466.0,
            "y": 369.0
        },
        {
            "x": 468.0,
            "y": 460.0
        },
        {
            "x": -364.0,
            "y": 468.0
        },
        {
            "x": -582.0,
            "y": 467.0
        },
        {
            "x": -369.0,
            "y": 599.0
        },
        {
            "x": -142.0,
            "y": 536.0
        },
        {
            "x": 76.0,
            "y": 596.0
        },
        {
            "x": 309.0,
            "y": 577.0
        },
        {
            "x": 637.0,
            "y": 781.0
        },
        {
            "x": 413.0,
            "y": 703.0
        },
        {
            "x": 416.0,
            "y": 792.0
        },
        {
            "x": 414.0,
            "y": 885.0
        },
        {
            "x": 1421.0,
            "y": 272.0
        },
        {
            "x": 2368.0,
            "y": 299.0
        },
        {
            "x": 2141.0,
            "y": 221.0
        },
        {
            "x": 2144.0,
            "y": 314.0
        },
        {
            "x": 2138.0,
            "y": 415.0
        },
        {
            "x": 1404.0,
            "y": 456.0
        },
        {
            "x": 1184.0,
            "y": 424.0
        },
        {
            "x": 1397.0,
            "y": 587.0
        },
        {
            "x": 1622.0,
            "y": 577.0
        },
        {
            "x": 1866.0,
            "y": 605.0
        },
        {
            "x": 1437.0,
            "y": 850.0
        },
        {
            "x": 1214.0,
            "y": 812.0
        },
        {
            "x": 1434.0,
            "y": 983.0
        },
        {
            "x": 1683.0,
            "y": 961.0
        },
        {
            "x": 2180.0,
            "y": 977.0
        },
        {
            "x": 1301.0,
            "y": 1115.0
        },
        {
            "x": 1958.0,
            "y": 958.0
        },
        {
            "x": 1057.0,
            "y": 1077.0
        },
        {
            "x": 1529.0,
            "y": 1224.0
        },
        {
            "x": 1745.0,
            "y": 1243.0
        },
        {
            "x": 1958.0,
            "y": 1246.0
        },
        {
            "x": 1524.0,
            "y": 1378.0
        },
        {
            "x": 1921.0,
            "y": 25.0
        },
        {
            "x": 1706.0,
            "y": -276.0
        },
        {
            "x": 942.0,
            "y": -208.0
        },
        {
            "x": 719.0,
            "y": -268.0
        },
        {
            "x": 939.0,
            "y": -78.0
        },
        {
            "x": 1174.0,
            "y": -129.0
        },
        {
            "x": 1932.0,
            "y": -164.0
        },
        {
            "x": 1698.0,
            "y": -50.0
        },
        {
            "x": 1401.0,
            "y": -70.0
        },
        {
            "x": 1697.0,
            "y": 42.0
        },
        {
            "x": 1713.0,
            "y": -167.0
        }
    ],
    "nodes": [
        {
            "key": 87,
            "string_id": "KeyboardNode"
        },
        {
            "string_id": "BranchNode"
        },
        {
            "string_id": "BranchNode"
        },
        {
            "operationIndex": 0,
            "string_id": "LogicalOperatorNode"
        },
        {
            "string_id": "AnimationInfoNode"
        },
        {
            "string": "Armature|jump",
            "string_id": "StringNode"
        },
        {
            "operationIndex": 0,
            "string_id": "StringOperatorNode"
        },
        {
            "animationName": "Armature|running",
            "string_id": "AnimationChangerNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "BooleanNode",
            "value": true
        },
        {
            "animationName": "Armature|idle",
            "string_id": "AnimationChangerNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "BooleanNode",
            "value": true
        },
        {
            "string_id": "AnimationInfoNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string": "Armature|jump",
            "string_id": "StringNode"
        },
        {
            "operationIndex": 0,
            "string_id": "StringOperatorNode"
        },
        {
            "string_id": "BranchNode"
        },
        {
            "operationIndex": 0,
            "string_id": "LogicalOperatorNode"
        },
        {
            "animationName": "Armature|idle",
            "string_id": "AnimationChangerNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "BooleanNode",
            "value": true
        },
        {
            "operationIndex": 0,
            "string_id": "LogicalOperatorNode"
        },
        {
            "key": 67,
            "string_id": "KeyboardNode"
        },
        {
            "animationName": "Armature|jump",
            "string_id": "AnimationChangerNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "BooleanNode",
            "value": false
        },
        {
            "operationIndex": 0,
            "string_id": "LogicalOperatorNode"
        },
        {
            "string_id": "AnimationInfoNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string": "Armature|jump",
            "string_id": "StringNode"
        },
        {
            "operationIndex": 0,
            "string_id": "StringOperatorNode"
        },
        {
            "string_id": "BranchNode"
        },
        {
            "string_id": "AnimationInfoNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string": "Armature|running",
            "string_id": "StringNode"
        },
        {
            "operationIndex": 0,
            "string_id": "StringOperatorNode"
        },
        {
            "string_id": "TransformModifierNode"
        },
        {
            "string_id": "TransformModifierNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "entityName": "Camera",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "VectorDecomposerNode"
        },
        {
            "operationIndex": 0,
            "string_id": "ScalarOperatorNode"
        },
        {
            "string_id": "VectorNode",
            "vector": {
                "w": 0.0,
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
            }
        },
        {
            "scalar": 3.141592025756836,
            "string_id": "ScalarNode"
        },
        {
            "string_id": "GravityModifierNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "AnimationInfoNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string": "Armature|jump",
            "string_id": "StringNode"
        },
        {
            "operationIndex": 0,
            "string_id": "StringOperatorNode"
        },
        {
            "string_id": "GravityModifierNode"
        },
        {
            "entityName": "Player",
            "string_id": "EntityFinderNode"
        },
        {
            "string_id": "BranchNode"
        },
        {
            "scalar": 1.0,
            "string_id": "ScalarNode"
        },
        {
            "scalar": 0.0,
            "string_id": "ScalarNode"
        }
    ]
}